// <auto-generated />
using System;
using DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BookHubDbContext))]
    [Migration("20250928144146_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 478, DateTimeKind.Local).AddTicks(9530),
                            Description = "The first volume in J.R.R. Tolkien's epic adventure, starting the journey to destroy the One Ring.",
                            ISBN = "978-0618260243",
                            Price = 12.99m,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 479, DateTimeKind.Local).AddTicks(1333),
                            Description = "The second volume of the trilogy, where the fellowship is scattered and the war for Middle-earth escalates.",
                            ISBN = "978-0618260281",
                            Price = 14.50m,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 479, DateTimeKind.Local).AddTicks(1353),
                            Description = "The final volume, chronicling the final destruction of the Ring and the ultimate fate of Middle-earth.",
                            ISBN = "978-0618260304",
                            Price = 15.99m,
                            Title = "The Return of the King"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 474, DateTimeKind.Local).AddTicks(7649),
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8729),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8762),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8766),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8769),
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8772),
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8774),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8777),
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8779),
                            Name = "Self-Help"
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8782),
                            Name = "Poetry"
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8784),
                            Name = "Young Adult"
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8787),
                            Name = "Children's"
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8789),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8792),
                            Name = "Action"
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 477, DateTimeKind.Local).AddTicks(8795),
                            Name = "Literary Fiction"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 479, DateTimeKind.Local).AddTicks(5128),
                            DateCreated = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stars = 5
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Created = new DateTime(2025, 9, 28, 16, 41, 45, 479, DateTimeKind.Local).AddTicks(6701),
                            DateCreated = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stars = 4
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Rating", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Book", "Book")
                        .WithMany("Ratings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Book", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
